// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgAESglbaU94Z6JI4NImzqCZMuEWIgCdQ',
    appId: '1:315776637831:android:8ebb9071e3994a33fa5122',
    messagingSenderId: '315776637831',
    projectId: 'dars6-b0f9a',
    databaseURL: 'https://dars6-b0f9a-default-rtdb.firebaseio.com',
    storageBucket: 'dars6-b0f9a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlnZKtaBNO-qOsCNB5ISqXZnEunOPpnkg',
    appId: '1:315776637831:ios:09cbb15398d7501cfa5122',
    messagingSenderId: '315776637831',
    projectId: 'dars6-b0f9a',
    databaseURL: 'https://dars6-b0f9a-default-rtdb.firebaseio.com',
    storageBucket: 'dars6-b0f9a.appspot.com',
    iosBundleId: 'com.example.telegram',
  );
}
